# -----------------------------------------------------
# AUTOSTART
# -----------------------------------------------------

# Theme
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = gsettings set org.gnome.desktop.interface color-scheme prefer-dark
exec-once = gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3

# Status bar
exec-once = waybar

# Notifications
exec-once = dunst

# Wallpaper
exec-once = swaybg -i ~/tools-bin/images/wallpapers/nord_scenary.png -m fill

# Authentication agent
exec-once = systemctl --user start hyprpolkitagent

# Idle manager
exec-once = hypridle

# Wayland and desktop env
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Auto mount USB devices
exec-once = udiskie
