[colors]
background = '#2828288e'
black = '#282828'
blue = '#fb4934'
cursor = '#d5c4a1'
cyan = '#b8bb26'
foreground = '#d5c4a1'
green = '#fabd2f'
magenta = '#83a598'
red = '#d3869b'
tabs = '#d5c4a1'
tabs-active = '#8ec07c'
white = '#d5c4a1'
yellow = '#d5c4a1'
dim-black = '#2828288e'
dim-blue = '#fb49348e'
dim-cyan = '#b8bb268e'
dim-foreground = '#d5c4a18e'
dim-green = '#fabd2f8e'
dim-magenta = '#83a5988e'
dim-red = '#d3869b8e'
dim-white = '#8ec07c8e'
dim-yellow = '#d5c4a18e'
light-black = '#fb4934'
light-blue = '#b8bb26'
light-cyan = '#fabd2f'
light-foreground = '#83a598'
light-green = '#d3869b'
light-magenta = '#8ec07c'
light-red = '#fbf1c7'
light-white = '#fb4934'
light-yellow = '#b8bb26'
